server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/Yorften/Documents/github/2222/microservices
          search-paths: configurations
          clone-on-start: true
